# Common vars
availability_zone: melbourne-qh2-uom

# Volumes and Mount Points
volumes:
  - vol_name: test-vol-1
    vol_size: 50
  - vol_name: test-vol-2
    vol_size: 50
  - vol_name: test-vol-3
    vol_size: 50
  - vol_name: test-vol-4
    vol_size: 50
  # - device: /dev/vdb
  #   mountpoint: /var/lib/docker
  # - device: /dev/vdc
  #   mountpoint: /data

# Security group
security_groups:
  - name: SSH
    description: "Security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: HTTP
    description: "Security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0 
  - name: HTTPS
    description: "Security group for HTTPS"
    protocol: tcp
    port_range_min: 443
    port_range_max: 443
    remote_ip_prefix: 0.0.0.0/0 

# Instance
instances:
  - name: test-1
    volumes: ['test-vol-1']
  - name: test-2
    volumes: ['test-vol-2']
  - name: test-3
    volumes: ['test-vol-3']
  - name: test-4
    volumes: ['test-vol-4']

instance_image: f3200167-dcd9-4a00-a99a-d2e8e57246d1
instance_key_name: hemanth_test
instance_flavor: uom.mse.2c9g
