---
- name: change node name in couchdb args
  replace:
    path: /etc/vm.args
    regexp: '-name data@127.0.0.1'
    replace: '-name data@{{inventory_hostname}}'

- name: Insert kernel max
  lineinfile:
    path: /etc/vm.args
    line: -kernel inet_dist_listen_max 9100
    
 - name: Insert kernel min
    lineinfile:
    path: /etc/vm.args
    line: -kernel inet_dist_listen_min 9150

# Run on all nodes
- name: Set up cluster
  uri:
    url:  http://admin:password@172.26.130.46:5984/_cluster_setup
    method: POST
    body:
      action: enable_cluster
      bind_address: 0.0.0.0
      username: admin
      password: password
      node_count: 4
    body_format: json
    headers:
      Content-Type: application/json


# Run on workers
- name: Connect to worker
  when : inventory_hostname in groups['workers']
  uri:
    url:  http:///admin:password@172.26.130.46:5984/_cluster_setup
    method: POST
    body:
      action: enable_cluster
      bind_address: 0.0.0.0
      username: admin
      password: password
      port: 5984
      remote_node: "{{ inventory_hostname }}"
      remote_current_user: admin
      remote_current_password: password
      node_count: 4
    body_format: json
    headers:
      Content-Type: application/json

# Run on workers
- name: Connect to cluster, adding node
  when : inventory_hostname in groups['configserver']
  uri:
    url:  http:///admin:password@172.26.130.46:5984/_cluster_setup
    method: POST
    body:
      action: add_node
      bind_address: 0.0.0.0
      username: admin
      password: password
      port: 5984
      remote_node: "{{ inventory_hostname }}"
      remote_current_user: admin
      remote_current_password: password
      node_count: 4
    body_format: json
    headers:
      Content-Type: application/json

# Complete set up
- name: Join node to cluster
  when: inventory_hostname in groups['configserver']
  uri:
    url:  http:///admin:password@172.26.130.46:5984/_cluster_setup
    method: POST
    body:
      action: finish_cluster
    body_format: json
    headers:
      Content-Type: application/json
    register: finished_cluster
# Verify complete set up
- name: Verify install
  when: inventory_hostname in groups['configserver']
  uri:
    url: 'http:///admin:password@172.26.130.46:5984/_cluster_setup'
    method: GET

# Check clustered nodes configuration
- name: Check clustered nodes configuration
  when: inventory_hostname in groups['configserver']
  uri:
    url: 'http:///admin:password@172.26.130.46:5984/_membership'
    method: GET
  register: membership