---
# Run on all nodes
- name: Set up cluster
  uri:
    url:  http://admin:password@172.26.130.46:5984/_cluster_setup
    method: POST
    body:
      action: enable_cluster
      bind_address: 0.0.0.0
      username: admin
      password: password
      node_count: 4
    body_format: json
    headers:
      Content-Type: application/json
    register: cluster_setup


# Run on workers
- name: Connect to worker
  with_items: "{{ groups['workers'] }}"
  uri:
    url:  http:///admin:password@172.26.130.46:5984/_cluster_setup
    method: POST
    body:
      action: enable_cluster
      bind_address: 0.0.0.0
      username: admin
      password: password
      port: 5984
      remote_node: "{{ hostvars[item].ansible_host }}"
      remote_current_user: admin
      remote_current_password: password
      node_count: 4
    body_format: json
    headers:
      Content-Type: application/json
    register: connect_nodes

# Run on workers
- name: Connect to cluster, adding node
  with_items: "{{ groups['workers'] }}"
  uri:
    url:  http:///admin:password@172.26.130.46:5984/_cluster_setup
    method: POST
    body:
      action: add_node
      bind_address: 0.0.0.0
      username: admin
      password: password
      port: 5984
      remote_node: "{{ hostvars[item].ansible_host }}"
      remote_current_user: admin
      remote_current_password: password
      node_count: 4
    body_format: json
    headers:
      Content-Type: application/json
    register: connect_nodes
# Complete set up
- name: Join node to cluster
  when: inventory_hostname in groups['configserver']
  uri:
    url:  http:///admin:password@172.26.130.46:5984/_cluster_setup
    method: POST
    body:
      action: finish_cluster
    body_format: json
    headers:
      Content-Type: application/json
    register: finished_cluster
# Verify complete set up
- name: Verify install
  when: inventory_hostname in groups['configserver']
  uri:
    url: 'http:///admin:password@172.26.130.46:5984/_cluster_setup'
    method: GET
  register: verification
# Check clustered nodes configuration
- name: Check clustered nodes configuration
  when: inventory_hostname in groups['configserver']
  uri:
    url: 'http:///admin:password@172.26.130.46:5984/_membership'
    method: GET
  register: membership