############################################################
# # Cluster and Cloud Computing (COMP90024) Assignment 2 # #
# # The University of Melbourne                          # #
# # Group Number: 48                                     # #
# # Authors:                                             # #
# # 1. Hemanth Pavan Kumar Challa - 1064637              # #
# # 2. Sai Varun Reddy Ankireddy  - 1152791              # #
# # 3. Abhisha Nirmalathas        - 913405               # # 
# # 4. Saharsha Karki             - 1042219              # #
# # 5. Reyham Noorjono            - 1018055              # #
############################################################

# Common vars
availability_zone: melbourne-qh2-uom

# Volumes and Mount Points
volumes:
  - vol_name: volume-1
    vol_size: 50
  - vol_name: volume-2
    vol_size: 50
  - vol_name: volume-3
    vol_size: 50
  - vol_name: volume-4
    vol_size: 50

# Security group
security_groups:
  - name: SSH
    description: "Security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0

  - name: HTTP
    description: "Security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0 

  - name: HTTPS
    description: "Security group for HTTPS"
    protocol: tcp
    port_range_min: 443
    port_range_max: 443
    remote_ip_prefix: 0.0.0.0/0 
  
  - name: Standalone CouchDB Cluster Port 1
    description: "Security group for Standalone CouchDB Cluster Port 1"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0 

  - name: Standalone CouchDB Cluster Port 2
    description: "Security group for Standalone CouchDB Cluster Port 2"
    protocol: tcp
    port_range_min: 5986
    port_range_max: 5986
    remote_ip_prefix: 0.0.0.0/0 

  - name: CouchDB Configure Port
    description: "Security group for CouchDB Configure Port"
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_ip_prefix: 0.0.0.0/0 
  
  - name: Node Front End Port
    description: "Security group for Node Front-End"
    protocol: tcp
    port_range_min: 3000
    port_range_max: 3000
    remote_ip_prefix: 0.0.0.0/0

  - name: CouchDB TCP Range
    description: "Security group for CouchDB TCP Range"
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9200
    remote_ip_prefix: 0.0.0.0/0 

# Instance
instances:
  - name: front-end
    volumes: ['volume-1']
  - name: cloud-harvester
    volumes: ['volume-2']
  - name: stream-harvester
    volumes: ['volume-3']
  - name: search-harvester
    volumes: ['volume-4']
 
# NeCTAR Ubuntu 18.04 LTS (Bionic) amd64    
instance_image: 45225edb-66d8-4fd0-bf41-132a31a18166 
instance_key_name: final_key
instance_flavor: uom.mse.2c9g
