---

############################################################
# # Cluster and Cloud Computing (COMP90024) Assignment 2 # #
# # The University of Melbourne                          # #
# # Group Number: 48                                     # #
# # Authors:                                             # #
# # 1. Hemanth Pavan Kumar Challa - 1064637              # #
# # 2. Sai Varun Reddy Ankireddy  - 1152791              # #
# # 3. Abhisha Nirmalathas        - 913405               # # 
# # 4. Saharsha Karki             - 1042219              # #
# # 5. Reyham Noorjono            - 1018055              # #
############################################################

    - name: Create an ext4 filesystem on /dev/vdb
      become: yes
      shell: mkfs.ext4 /dev/vdb
      
    - name: Create directory if it does not exist
      file:
        path: /home/ubuntu/data
        state: directory
        mode: '0755'
    
    - name: Mount volume
      become: yes
      mount:
        path: /home/ubuntu/data
        src: /dev/vdb
        state: mounted
        fstype: ext4