---
############################################################
# # Cluster and Cloud Computing (COMP90024) Assignment 2 # #
# # The University of Melbourne                          # #
# # Group Number: 48                                     # #
# # Authors:                                             # #
# # 1. Hemanth Pavan Kumar Challa - 1064637              # #
# # 2. Sai Varun Reddy Ankireddy  - 1152791              # #
# # 3. Abhisha Nirmalathas        - 913405               # # 
# # 4. Saharsha Karki             - 1042219              # #
# # 5. Reyham Noorjono            - 1018055              # #
############################################################


# Create an instance on NeCTAR
- name: Create an instance
  os_server:
    name: '{{ item.name }}'
    image: '{{ instance_image }}'
    key_name: '{{ instance_key_name }}'
    flavor: '{{ instance_flavor }}'
    availability_zone: '{{ availability_zone }}'
    security_groups: '{{ sg_names }}'
    volumes: '{{ item.volumes }}'
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  loop: '{{ instances }}'
  register: os_instance

- debug:
    msg: "Instance {{ item.openstack.name }} has been created. IP address is {{ item.openstack.public_v4 }}"
  loop: '{{ os_instance.results }}'
  when: item.openstack is defined

- name: Wait for connection
  wait_for:
    host: "{{ item.openstack.public_v4 }}"
    port: 22
    timeout: 120
    search_regex: OpenSSH
  loop: '{{ os_instance.results }}'
  when: item.openstack is defined

# Add hosts to Ansible in-memory inventory
- name: Add host
  add_host:
    name: '{{ item.openstack.public_v4 }}'
    groups: Testgroup
  loop: '{{ os_instance.results }}'
  when: item.openstack is defined
