---
# CREATES SINGLE SHARDED REPLICATED DATABASE
- name: Create database
  when: inventory_hostname in groups['configserver']
  uri:
    url: http://admin:admin@172.26.133.84:5984/database?n=4&q=1
    method: PUT
    url_username: admin
    status_code: 201
    validate_certs: no