---
- name: Install git
  become: yes
  pip:
    name: ['git']
    state: latest

- name: Install python3 pip
  become: yes
  apt:
    name: ['python3-pip']
    state: latest
    update_cache: yes
- name: Install python3 venv
  become: yes
  apt:
    name: ['python3-venv']
    state: latest  
    update_cache: yes
  
- name: Update pip
  become: yes
  pip:
    name: ['pip']
    state: latest

- name: Install other dependencies
  become: yes
  pip:
    requirements: /requirements.txt

- name: Install GNUPG certificates
  become: yes
  apt:
    pkg:
      - apt-transport-https
      - gnupg ca-certificates
    state: latest
    update_cache: yes

- name: Enable CouchDB package repository
  shell: echo "deb https://apache.bintray.com/couchdb-deb bionic main"  | sudo tee -a /etc/apt/sources.list.d/couchdb.list
- name: Add key server
  shell: sudo apt-key adv --keyserver keyserver.ubuntu.com --keyserver-options http-proxy=http://wwwproxy.unimelb.edu.au --recv-keys 8756C4F765C9AC3CB6B85D62379CE192D401AB61
- name: Update
  become: yes
  apt:
    update_cache: yes

- name: Install couchDB
  become: yes
  apt:
    name: ['couchdb']
    state: latest
    update_cache: yes


