- hosts: localhost
  vars_files:
    - host_vars/inventory.yaml
  gather_facts: true

  roles:
    - role: openstack-common
    - role: openstack-images
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance

- name: SSH Details
  hosts: openstack.public_v4
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: ubuntu
    ansible_ssh_private_key_file: /hemanth_test.pem
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  roles: 
    - role: openstack-proxy
    - role: openstack-dependencies
    # Install NodeJS
    # - geerlingguy.nodejs 